name: terraform destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: string
      region:
        required: false
        type: string
      role:
        required: false
        type: string
jobs:
  deploy:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::471112939810:role/Everything
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: set bucket key based on repo name without "-terraform" suffix
        run: echo "BUCKET_KEY=$(basename -s -terraform ${{ github.event.repository.name }})" >> $GITHUB_ENV

      - name: set bucket name based on environment
        run: echo "BUCKET_NAME=ryanh-github-oidc-terraform-dev" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="bucket=${{ env.BUCKET_NAME }}" \
          -backend-config="key=${{ env.BUCKET_KEY }}" \
          -backend-config="region=us-east-1"

      - name: Terraform Apply
        if: github.ref_name == 'dev' || github.ref_name == 'qa' || github.ref_name == 'prod'
        run: terraform destroy --auto-approve
