name: dev terraform w/ oidc
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-deploy:
    uses: ryan-hoofard/reusable-workflows/.github/workflows/terraform-aws.yml@refs/heads/main
    permissions:
      id-token: write
      contents: read
    with:
      region: us-east-1
      environment: dev
      role: arn:aws:iam::381492128561:role/github-oidc



  
