name: dev terraform w/ oidc
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-deploy:
    uses: ryan-hoofard/github-aws-oidc-terraform/.github/workflows/reusable-terraform-workflow.yml@dev
    permissions:
      id-token: write
      contents: read
    with:
      region: us-east-1
      environment: dev
      role: arn:aws:iam::381492032511:role/Everything



  
