name: dev terraform w/ oidc
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-plan:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      region: us-west-2
      environment: dev
      apply: false
    secrets: ${{ secrets.AWS_ROLE_DEV }}

  dev-apply:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      region: us-west-2
      environment: dev
      apply: true
    secrets: 
      aws_role: ${{ secrets.AWS_ROLE_DEV }}


  